# Generated by Django 4.0.3 on 2022-04-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('image3', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('catego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.categories')),
            ],
        ),
    ]
