# Generated by Django 4.0.3 on 2022-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='orderd',
            field=models.BooleanField(default=False),
        ),
    ]
